package db;
// Generated Aug 30, 2017 1:08:20 PM by Hibernate Tools 4.3.1


import java.util.HashSet;
import java.util.Set;

/**
 * Aerodromi generated by hbm2java
 */
public class Aerodromi  implements java.io.Serializable {


     private String iata;
     private String naziv;
     private String grad;
     private String zemlja;
     private int brojPisti;
     private Set gejtoviiterminalis = new HashSet(0);

    public Aerodromi() {
    }

	
    public Aerodromi(String iata, String naziv, String grad, String zemlja, int brojPisti) {
        this.iata = iata;
        this.naziv = naziv;
        this.grad = grad;
        this.zemlja = zemlja;
        this.brojPisti = brojPisti;
    }
    public Aerodromi(String iata, String naziv, String grad, String zemlja, int brojPisti, Set gejtoviiterminalis) {
       this.iata = iata;
       this.naziv = naziv;
       this.grad = grad;
       this.zemlja = zemlja;
       this.brojPisti = brojPisti;
       this.gejtoviiterminalis = gejtoviiterminalis;
    }
   
    public String getIata() {
        return this.iata;
    }
    
    public void setIata(String iata) {
        this.iata = iata;
    }
    public String getNaziv() {
        return this.naziv;
    }
    
    public void setNaziv(String naziv) {
        this.naziv = naziv;
    }
    public String getGrad() {
        return this.grad;
    }
    
    public void setGrad(String grad) {
        this.grad = grad;
    }
    public String getZemlja() {
        return this.zemlja;
    }
    
    public void setZemlja(String zemlja) {
        this.zemlja = zemlja;
    }
    public int getBrojPisti() {
        return this.brojPisti;
    }
    
    public void setBrojPisti(int brojPisti) {
        this.brojPisti = brojPisti;
    }
    public Set getGejtoviiterminalis() {
        return this.gejtoviiterminalis;
    }
    
    public void setGejtoviiterminalis(Set gejtoviiterminalis) {
        this.gejtoviiterminalis = gejtoviiterminalis;
    }




}


