package db;
// Generated Aug 30, 2017 1:08:20 PM by Hibernate Tools 4.3.1


import java.util.HashSet;
import java.util.Set;

/**
 * AvioKompanije generated by hbm2java
 */
public class AvioKompanije  implements java.io.Serializable {


     private int id;
     private String naziv;
     private String adresa;
     private String zemlja;
     private String webadresa;
     private String email;
     private Set iznajmljivanjes = new HashSet(0);
     private Set korisnicis = new HashSet(0);
     private Set avionisForIznajmljen = new HashSet(0);
     private Set avionisForIdKompanije = new HashSet(0);

    public AvioKompanije() {
    }

	
    public AvioKompanije(int id, String naziv, String adresa, String zemlja, String webadresa, String email) {
        this.id = id;
        this.naziv = naziv;
        this.adresa = adresa;
        this.zemlja = zemlja;
        this.webadresa = webadresa;
        this.email = email;
    }
    public AvioKompanije(int id, String naziv, String adresa, String zemlja, String webadresa, String email, Set iznajmljivanjes, Set korisnicis, Set avionisForIznajmljen, Set avionisForIdKompanije) {
       this.id = id;
       this.naziv = naziv;
       this.adresa = adresa;
       this.zemlja = zemlja;
       this.webadresa = webadresa;
       this.email = email;
       this.iznajmljivanjes = iznajmljivanjes;
       this.korisnicis = korisnicis;
       this.avionisForIznajmljen = avionisForIznajmljen;
       this.avionisForIdKompanije = avionisForIdKompanije;
    }
   
    public int getId() {
        return this.id;
    }
    
    public void setId(int id) {
        this.id = id;
    }
    public String getNaziv() {
        return this.naziv;
    }
    
    public void setNaziv(String naziv) {
        this.naziv = naziv;
    }
    public String getAdresa() {
        return this.adresa;
    }
    
    public void setAdresa(String adresa) {
        this.adresa = adresa;
    }
    public String getZemlja() {
        return this.zemlja;
    }
    
    public void setZemlja(String zemlja) {
        this.zemlja = zemlja;
    }
    public String getWebadresa() {
        return this.webadresa;
    }
    
    public void setWebadresa(String webadresa) {
        this.webadresa = webadresa;
    }
    public String getEmail() {
        return this.email;
    }
    
    public void setEmail(String email) {
        this.email = email;
    }
    public Set getIznajmljivanjes() {
        return this.iznajmljivanjes;
    }
    
    public void setIznajmljivanjes(Set iznajmljivanjes) {
        this.iznajmljivanjes = iznajmljivanjes;
    }
    public Set getKorisnicis() {
        return this.korisnicis;
    }
    
    public void setKorisnicis(Set korisnicis) {
        this.korisnicis = korisnicis;
    }
    public Set getAvionisForIznajmljen() {
        return this.avionisForIznajmljen;
    }
    
    public void setAvionisForIznajmljen(Set avionisForIznajmljen) {
        this.avionisForIznajmljen = avionisForIznajmljen;
    }
    public Set getAvionisForIdKompanije() {
        return this.avionisForIdKompanije;
    }
    
    public void setAvionisForIdKompanije(Set avionisForIdKompanije) {
        this.avionisForIdKompanije = avionisForIdKompanije;
    }




}


