package db;
// Generated Aug 30, 2017 1:08:20 PM by Hibernate Tools 4.3.1


import java.util.HashSet;
import java.util.Set;

/**
 * Gejtoviiterminali generated by hbm2java
 */
public class Gejtoviiterminali  implements java.io.Serializable {


     private String gejt;
     private Aerodromi aerodromi;
     private int terminal;
     private Set letovisForArrgejt = new HashSet(0);
     private Set letovisForUrggejt = new HashSet(0);
     private Set letovisForDepgejt = new HashSet(0);

    public Gejtoviiterminali() {
    }

	
    public Gejtoviiterminali(String gejt, Aerodromi aerodromi, int terminal) {
        this.gejt = gejt;
        this.aerodromi = aerodromi;
        this.terminal = terminal;
    }
    public Gejtoviiterminali(String gejt, Aerodromi aerodromi, int terminal, Set letovisForArrgejt, Set letovisForUrggejt, Set letovisForDepgejt) {
       this.gejt = gejt;
       this.aerodromi = aerodromi;
       this.terminal = terminal;
       this.letovisForArrgejt = letovisForArrgejt;
       this.letovisForUrggejt = letovisForUrggejt;
       this.letovisForDepgejt = letovisForDepgejt;
    }
   
    public String getGejt() {
        return this.gejt;
    }
    
    public void setGejt(String gejt) {
        this.gejt = gejt;
    }
    public Aerodromi getAerodromi() {
        return this.aerodromi;
    }
    
    public void setAerodromi(Aerodromi aerodromi) {
        this.aerodromi = aerodromi;
    }
    public int getTerminal() {
        return this.terminal;
    }
    
    public void setTerminal(int terminal) {
        this.terminal = terminal;
    }
    public Set getLetovisForArrgejt() {
        return this.letovisForArrgejt;
    }
    
    public void setLetovisForArrgejt(Set letovisForArrgejt) {
        this.letovisForArrgejt = letovisForArrgejt;
    }
    public Set getLetovisForUrggejt() {
        return this.letovisForUrggejt;
    }
    
    public void setLetovisForUrggejt(Set letovisForUrggejt) {
        this.letovisForUrggejt = letovisForUrggejt;
    }
    public Set getLetovisForDepgejt() {
        return this.letovisForDepgejt;
    }
    
    public void setLetovisForDepgejt(Set letovisForDepgejt) {
        this.letovisForDepgejt = letovisForDepgejt;
    }




}


