package db;
// Generated Aug 30, 2017 1:08:20 PM by Hibernate Tools 4.3.1



/**
 * Gostirezervacije generated by hbm2java
 */
public class Gostirezervacije  implements java.io.Serializable {


     private Integer id;
     private int idLeta;
     private String imePrezime;
     private String brojPasosa;
     private String brojKartice;
     private boolean odobreno;
     private String sifra;
     private int odrasli;

    public Gostirezervacije() {
    }

    public Gostirezervacije(int idLeta, String imePrezime, String brojPasosa, String brojKartice, boolean odobreno, String sifra, int odrasli) {
       this.idLeta = idLeta;
       this.imePrezime = imePrezime;
       this.brojPasosa = brojPasosa;
       this.brojKartice = brojKartice;
       this.odobreno = odobreno;
       this.sifra = sifra;
       this.odrasli = odrasli;
    }
   
    public Integer getId() {
        return this.id;
    }
    
    public void setId(Integer id) {
        this.id = id;
    }
    public int getIdLeta() {
        return this.idLeta;
    }
    
    public void setIdLeta(int idLeta) {
        this.idLeta = idLeta;
    }
    public String getImePrezime() {
        return this.imePrezime;
    }
    
    public void setImePrezime(String imePrezime) {
        this.imePrezime = imePrezime;
    }
    public String getBrojPasosa() {
        return this.brojPasosa;
    }
    
    public void setBrojPasosa(String brojPasosa) {
        this.brojPasosa = brojPasosa;
    }
    public String getBrojKartice() {
        return this.brojKartice;
    }
    
    public void setBrojKartice(String brojKartice) {
        this.brojKartice = brojKartice;
    }
    public boolean isOdobreno() {
        return this.odobreno;
    }
    
    public void setOdobreno(boolean odobreno) {
        this.odobreno = odobreno;
    }
    public String getSifra() {
        return this.sifra;
    }
    
    public void setSifra(String sifra) {
        this.sifra = sifra;
    }
    public int getOdrasli() {
        return this.odrasli;
    }
    
    public void setOdrasli(int odrasli) {
        this.odrasli = odrasli;
    }




}


