package db;
// Generated Aug 30, 2017 1:08:20 PM by Hibernate Tools 4.3.1


import java.util.Date;
import java.util.HashSet;
import java.util.Set;

/**
 * Korisnici generated by hbm2java
 */
public class Korisnici  implements java.io.Serializable {


     private String korIme;
     private AvioKompanije avioKompanije;
     private String ime;
     private String prezime;
     private String email;
     private String lozinka;
     private String pol;
     private String pozicija;
     private int prviLogin;
     private int odobreno;
     private Date datumRodjenja;
     private Set licences = new HashSet(0);
     private Set osobljeletas = new HashSet(0);

    public Korisnici() {
    }

	
    public Korisnici(String korIme, AvioKompanije avioKompanije, String ime, String prezime, String email, String lozinka, String pol, String pozicija, int prviLogin, int odobreno, Date datumRodjenja) {
        this.korIme = korIme;
        this.avioKompanije = avioKompanije;
        this.ime = ime;
        this.prezime = prezime;
        this.email = email;
        this.lozinka = lozinka;
        this.pol = pol;
        this.pozicija = pozicija;
        this.prviLogin = prviLogin;
        this.odobreno = odobreno;
        this.datumRodjenja = datumRodjenja;
    }
    public Korisnici(String korIme, AvioKompanije avioKompanije, String ime, String prezime, String email, String lozinka, String pol, String pozicija, int prviLogin, int odobreno, Date datumRodjenja, Set licences, Set osobljeletas) {
       this.korIme = korIme;
       this.avioKompanije = avioKompanije;
       this.ime = ime;
       this.prezime = prezime;
       this.email = email;
       this.lozinka = lozinka;
       this.pol = pol;
       this.pozicija = pozicija;
       this.prviLogin = prviLogin;
       this.odobreno = odobreno;
       this.datumRodjenja = datumRodjenja;
       this.licences = licences;
       this.osobljeletas = osobljeletas;
    }
   
    public String getKorIme() {
        return this.korIme;
    }
    
    public void setKorIme(String korIme) {
        this.korIme = korIme;
    }
    public AvioKompanije getAvioKompanije() {
        return this.avioKompanije;
    }
    
    public void setAvioKompanije(AvioKompanije avioKompanije) {
        this.avioKompanije = avioKompanije;
    }
    public String getIme() {
        return this.ime;
    }
    
    public void setIme(String ime) {
        this.ime = ime;
    }
    public String getPrezime() {
        return this.prezime;
    }
    
    public void setPrezime(String prezime) {
        this.prezime = prezime;
    }
    public String getEmail() {
        return this.email;
    }
    
    public void setEmail(String email) {
        this.email = email;
    }
    public String getLozinka() {
        return this.lozinka;
    }
    
    public void setLozinka(String lozinka) {
        this.lozinka = lozinka;
    }
    public String getPol() {
        return this.pol;
    }
    
    public void setPol(String pol) {
        this.pol = pol;
    }
    public String getPozicija() {
        return this.pozicija;
    }
    
    public void setPozicija(String pozicija) {
        this.pozicija = pozicija;
    }
    public int getPrviLogin() {
        return this.prviLogin;
    }
    
    public void setPrviLogin(int prviLogin) {
        this.prviLogin = prviLogin;
    }
    public int getOdobreno() {
        return this.odobreno;
    }
    
    public void setOdobreno(int odobreno) {
        this.odobreno = odobreno;
    }
    public Date getDatumRodjenja() {
        return this.datumRodjenja;
    }
    
    public void setDatumRodjenja(Date datumRodjenja) {
        this.datumRodjenja = datumRodjenja;
    }
    public Set getLicences() {
        return this.licences;
    }
    
    public void setLicences(Set licences) {
        this.licences = licences;
    }
    public Set getOsobljeletas() {
        return this.osobljeletas;
    }
    
    public void setOsobljeletas(Set osobljeletas) {
        this.osobljeletas = osobljeletas;
    }




}


