package db;
// Generated Aug 30, 2017 1:08:20 PM by Hibernate Tools 4.3.1



/**
 * Letoviradari generated by hbm2java
 */
public class Letoviradari  implements java.io.Serializable {


     private Integer id;
     private Letovi letovi;
     private Radarskicentri radarskicentri;
     private Double brzina;
     private Double ostatak;

    public Letoviradari() {
    }

	
    public Letoviradari(Letovi letovi, Radarskicentri radarskicentri) {
        this.letovi = letovi;
        this.radarskicentri = radarskicentri;
    }
    public Letoviradari(Letovi letovi, Radarskicentri radarskicentri, Double brzina, Double ostatak) {
       this.letovi = letovi;
       this.radarskicentri = radarskicentri;
       this.brzina = brzina;
       this.ostatak = ostatak;
    }
   
    public Integer getId() {
        return this.id;
    }
    
    public void setId(Integer id) {
        this.id = id;
    }
    public Letovi getLetovi() {
        return this.letovi;
    }
    
    public void setLetovi(Letovi letovi) {
        this.letovi = letovi;
    }
    public Radarskicentri getRadarskicentri() {
        return this.radarskicentri;
    }
    
    public void setRadarskicentri(Radarskicentri radarskicentri) {
        this.radarskicentri = radarskicentri;
    }
    public Double getBrzina() {
        return this.brzina;
    }
    
    public void setBrzina(Double brzina) {
        this.brzina = brzina;
    }
    public Double getOstatak() {
        return this.ostatak;
    }
    
    public void setOstatak(Double ostatak) {
        this.ostatak = ostatak;
    }




}


