package db;
// Generated Aug 30, 2017 1:08:20 PM by Hibernate Tools 4.3.1


import java.util.Date;
import java.util.HashSet;
import java.util.Set;

/**
 * Letovi generated by hbm2java
 */
public class Letovi  implements java.io.Serializable {


     private int id;
     private Avioni avioni;
     private Gejtoviiterminali gejtoviiterminaliByArrgejt;
     private Gejtoviiterminali gejtoviiterminaliByUrggejt;
     private Gejtoviiterminali gejtoviiterminaliByDepgejt;
     private int trajanjeLeta;
     private Date vremePoletanja;
     private Date planiranoVreme;
     private Date ocekivanoVreme;
     private Date vremeSletanja;
     private String status;
     private Set osobljeletas = new HashSet(0);
     private Set letoviradaris = new HashSet(0);

    public Letovi() {
    }

	
    public Letovi(int id, Avioni avioni, Gejtoviiterminali gejtoviiterminaliByArrgejt, Gejtoviiterminali gejtoviiterminaliByDepgejt, int trajanjeLeta, Date vremePoletanja, Date planiranoVreme, Date ocekivanoVreme, String status) {
        this.id = id;
        this.avioni = avioni;
        this.gejtoviiterminaliByArrgejt = gejtoviiterminaliByArrgejt;
        this.gejtoviiterminaliByDepgejt = gejtoviiterminaliByDepgejt;
        this.trajanjeLeta = trajanjeLeta;
        this.vremePoletanja = vremePoletanja;
        this.planiranoVreme = planiranoVreme;
        this.ocekivanoVreme = ocekivanoVreme;
        this.status = status;
    }
    public Letovi(int id, Avioni avioni, Gejtoviiterminali gejtoviiterminaliByArrgejt, Gejtoviiterminali gejtoviiterminaliByUrggejt, Gejtoviiterminali gejtoviiterminaliByDepgejt, int trajanjeLeta, Date vremePoletanja, Date planiranoVreme, Date ocekivanoVreme, Date vremeSletanja, String status, Set osobljeletas, Set letoviradaris) {
       this.id = id;
       this.avioni = avioni;
       this.gejtoviiterminaliByArrgejt = gejtoviiterminaliByArrgejt;
       this.gejtoviiterminaliByUrggejt = gejtoviiterminaliByUrggejt;
       this.gejtoviiterminaliByDepgejt = gejtoviiterminaliByDepgejt;
       this.trajanjeLeta = trajanjeLeta;
       this.vremePoletanja = vremePoletanja;
       this.planiranoVreme = planiranoVreme;
       this.ocekivanoVreme = ocekivanoVreme;
       this.vremeSletanja = vremeSletanja;
       this.status = status;
       this.osobljeletas = osobljeletas;
       this.letoviradaris = letoviradaris;
    }
   
    public int getId() {
        return this.id;
    }
    
    public void setId(int id) {
        this.id = id;
    }
    public Avioni getAvioni() {
        return this.avioni;
    }
    
    public void setAvioni(Avioni avioni) {
        this.avioni = avioni;
    }
    public Gejtoviiterminali getGejtoviiterminaliByArrgejt() {
        return this.gejtoviiterminaliByArrgejt;
    }
    
    public void setGejtoviiterminaliByArrgejt(Gejtoviiterminali gejtoviiterminaliByArrgejt) {
        this.gejtoviiterminaliByArrgejt = gejtoviiterminaliByArrgejt;
    }
    public Gejtoviiterminali getGejtoviiterminaliByUrggejt() {
        return this.gejtoviiterminaliByUrggejt;
    }
    
    public void setGejtoviiterminaliByUrggejt(Gejtoviiterminali gejtoviiterminaliByUrggejt) {
        this.gejtoviiterminaliByUrggejt = gejtoviiterminaliByUrggejt;
    }
    public Gejtoviiterminali getGejtoviiterminaliByDepgejt() {
        return this.gejtoviiterminaliByDepgejt;
    }
    
    public void setGejtoviiterminaliByDepgejt(Gejtoviiterminali gejtoviiterminaliByDepgejt) {
        this.gejtoviiterminaliByDepgejt = gejtoviiterminaliByDepgejt;
    }
    public int getTrajanjeLeta() {
        return this.trajanjeLeta;
    }
    
    public void setTrajanjeLeta(int trajanjeLeta) {
        this.trajanjeLeta = trajanjeLeta;
    }
    public Date getVremePoletanja() {
        return this.vremePoletanja;
    }
    
    public void setVremePoletanja(Date vremePoletanja) {
        this.vremePoletanja = vremePoletanja;
    }
    public Date getPlaniranoVreme() {
        return this.planiranoVreme;
    }
    
    public void setPlaniranoVreme(Date planiranoVreme) {
        this.planiranoVreme = planiranoVreme;
    }
    public Date getOcekivanoVreme() {
        return this.ocekivanoVreme;
    }
    
    public void setOcekivanoVreme(Date ocekivanoVreme) {
        this.ocekivanoVreme = ocekivanoVreme;
    }
    public Date getVremeSletanja() {
        return this.vremeSletanja;
    }
    
    public void setVremeSletanja(Date vremeSletanja) {
        this.vremeSletanja = vremeSletanja;
    }
    public String getStatus() {
        return this.status;
    }
    
    public void setStatus(String status) {
        this.status = status;
    }
    public Set getOsobljeletas() {
        return this.osobljeletas;
    }
    
    public void setOsobljeletas(Set osobljeletas) {
        this.osobljeletas = osobljeletas;
    }
    public Set getLetoviradaris() {
        return this.letoviradaris;
    }
    
    public void setLetoviradaris(Set letoviradaris) {
        this.letoviradaris = letoviradaris;
    }




}


