package db;
// Generated Aug 30, 2017 1:08:20 PM by Hibernate Tools 4.3.1



/**
 * Licence generated by hbm2java
 */
public class Licence  implements java.io.Serializable {


     private Integer id;
     private Korisnici korisnici;
     private String lic;
     private String tip;

    public Licence() {
    }

    public Licence(Korisnici korisnici, String lic, String tip) {
       this.korisnici = korisnici;
       this.lic = lic;
       this.tip = tip;
    }
   
    public Integer getId() {
        return this.id;
    }
    
    public void setId(Integer id) {
        this.id = id;
    }
    public Korisnici getKorisnici() {
        return this.korisnici;
    }
    
    public void setKorisnici(Korisnici korisnici) {
        this.korisnici = korisnici;
    }
    public String getLic() {
        return this.lic;
    }
    
    public void setLic(String lic) {
        this.lic = lic;
    }
    public String getTip() {
        return this.tip;
    }
    
    public void setTip(String tip) {
        this.tip = tip;
    }




}


