package db;
// Generated Aug 30, 2017 1:08:20 PM by Hibernate Tools 4.3.1



/**
 * Osobljeleta generated by hbm2java
 */
public class Osobljeleta  implements java.io.Serializable {


     private Integer id;
     private Korisnici korisnici;
     private Letovi letovi;

    public Osobljeleta() {
    }

    public Osobljeleta(Korisnici korisnici, Letovi letovi) {
       this.korisnici = korisnici;
       this.letovi = letovi;
    }
   
    public Integer getId() {
        return this.id;
    }
    
    public void setId(Integer id) {
        this.id = id;
    }
    public Korisnici getKorisnici() {
        return this.korisnici;
    }
    
    public void setKorisnici(Korisnici korisnici) {
        this.korisnici = korisnici;
    }
    public Letovi getLetovi() {
        return this.letovi;
    }
    
    public void setLetovi(Letovi letovi) {
        this.letovi = letovi;
    }




}


