package db;
// Generated Aug 30, 2017 1:08:20 PM by Hibernate Tools 4.3.1


import java.util.HashSet;
import java.util.Set;

/**
 * Proizvodjaci generated by hbm2java
 */
public class Proizvodjaci  implements java.io.Serializable {


     private int id;
     private String ime;
     private String grad;
     private String drzava;
     private Set avionis = new HashSet(0);

    public Proizvodjaci() {
    }

	
    public Proizvodjaci(int id, String ime, String grad, String drzava) {
        this.id = id;
        this.ime = ime;
        this.grad = grad;
        this.drzava = drzava;
    }
    public Proizvodjaci(int id, String ime, String grad, String drzava, Set avionis) {
       this.id = id;
       this.ime = ime;
       this.grad = grad;
       this.drzava = drzava;
       this.avionis = avionis;
    }
   
    public int getId() {
        return this.id;
    }
    
    public void setId(int id) {
        this.id = id;
    }
    public String getIme() {
        return this.ime;
    }
    
    public void setIme(String ime) {
        this.ime = ime;
    }
    public String getGrad() {
        return this.grad;
    }
    
    public void setGrad(String grad) {
        this.grad = grad;
    }
    public String getDrzava() {
        return this.drzava;
    }
    
    public void setDrzava(String drzava) {
        this.drzava = drzava;
    }
    public Set getAvionis() {
        return this.avionis;
    }
    
    public void setAvionis(Set avionis) {
        this.avionis = avionis;
    }




}


