package db;
// Generated Aug 30, 2017 1:08:20 PM by Hibernate Tools 4.3.1


import java.math.BigDecimal;
import java.util.HashSet;
import java.util.Set;

/**
 * Radarskicentri generated by hbm2java
 */
public class Radarskicentri  implements java.io.Serializable {


     private Integer id;
     private String grad;
     private String zemlja;
     private BigDecimal duzina;
     private BigDecimal sirina;
     private Set letoviradaris = new HashSet(0);

    public Radarskicentri() {
    }

	
    public Radarskicentri(String grad, String zemlja, BigDecimal duzina, BigDecimal sirina) {
        this.grad = grad;
        this.zemlja = zemlja;
        this.duzina = duzina;
        this.sirina = sirina;
    }
    public Radarskicentri(String grad, String zemlja, BigDecimal duzina, BigDecimal sirina, Set letoviradaris) {
       this.grad = grad;
       this.zemlja = zemlja;
       this.duzina = duzina;
       this.sirina = sirina;
       this.letoviradaris = letoviradaris;
    }
   
    public Integer getId() {
        return this.id;
    }
    
    public void setId(Integer id) {
        this.id = id;
    }
    public String getGrad() {
        return this.grad;
    }
    
    public void setGrad(String grad) {
        this.grad = grad;
    }
    public String getZemlja() {
        return this.zemlja;
    }
    
    public void setZemlja(String zemlja) {
        this.zemlja = zemlja;
    }
    public BigDecimal getDuzina() {
        return this.duzina;
    }
    
    public void setDuzina(BigDecimal duzina) {
        this.duzina = duzina;
    }
    public BigDecimal getSirina() {
        return this.sirina;
    }
    
    public void setSirina(BigDecimal sirina) {
        this.sirina = sirina;
    }
    public Set getLetoviradaris() {
        return this.letoviradaris;
    }
    
    public void setLetoviradaris(Set letoviradaris) {
        this.letoviradaris = letoviradaris;
    }




}


